import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";
import About from "@/components/About";
import Services from "@/components/Services";
import Projects from "@/components/Projects";
import Contact from "@/components/Contact";
import Footer from "@/components/Footer";
import Script from "next/script";
import Script1 from "@/components/Script";

const poppins = Poppins({
  subsets: ["latin"], weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
})

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" className="text-[62.5%] overflow-x-hidden">
      <head>
        <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'></link>
      </head>
      <body
        className={`${poppins.className} ${poppins.className} antialiased m-0 p-0 box-border no-underline border-none outline-none scroll-smooth`}
      >
        {children}
        <About />
        <Services />
        <Projects />
        <Contact />
        <Footer />
        <Script src="https://unpkg.com/scrollreveal" strategy="beforeInteractive" />
        <Script1 />
      </body>
    </html>
  );
}
